### model
model_name_or_path: 

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset 
dataset: OntoTune_sft
template: llama3
cutoff_len: 4096
max_samples: 1000000000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/OntoTune_sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
#fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 24
eval_strategy: steps
eval_steps: 10000
